export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const TOGGLE_SWITCH = "TOGGLE_SWITCH";

export const API_FINISHED = "API_FINISHED";
